imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@MainBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.product_images: /images/
    app.path.specialitylist_images: /images/specialitylist/

framework:
    #esi:             ~
    translator:      { fallback: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Gregwar Image Bundle Configuration
gregwar_image:
    throw_exception: true

# Gregwar Captcha Bundle Configuration
gregwar_captcha:

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"

        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"


    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Assetic Bundle Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: true
    #bundles:        []
    #java: /usr/bin/java
    read_from: "%kernel.root_dir%/../../public_html"
    filters:
        cssrewrite: ~
        uglifyjs:
            bin:
        uglifycss:
            bin:
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Elastica Bundle Configuation
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    serializer:
        callback_class: FOS\ElasticaBundle\Serializer\Callback
        serializer: serializer
    indexes:
        odellya:
            client: default
            types:
                Application:
                    mappings: ~
                    persistence:
                        driver: orm # orm, mongodb, propel are available
                        model:  MainBundle\Entity\Application
                        provider: ~
                


# FOSUserBundle Configuration
fos_user:
    service:
        mailer: fos_user.mailer.twig_swift
    db_driver: orm
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
        confirmation:
            enabled: false
        form:
            type: bambou_user_registration
            validation_groups: [CustomRegistration, Default]
    resetting:
        email:
            from_email:
                address: contact@bamboudafrique.com
                sender_name: "Restaurant Bambou d Afrique"

easy_admin:
    entities:
        # Entities to be handled in the admin panel
        Product:
            class: MainBundle\Entity\Product
            list:
                title: "Plats"
                fields:
                    - "title"
                    - "price"
                    - "tva"
                    - "available"
                    - "productName"

            show:
                fields:
                    - "title"
                    - "price"
                    - "available"
                    - "productName"
                    - { property: 'productFile', type: 'vich_image', base_path: '/images/' }
            form:
                fields:
                    - "title"
                    - "price"
                    - "available"
                    - "description"
                    - "productName"
                    - { property: 'productFile', type: 'vich_image', label: 'Fichier image', base_path: '/images/'  }

        Commande:
            class: MainBundle\Entity\Commande
            list:
                title: "Commandes récentes"

        User:
            list:
                title: "Liste de membres"
            class: UserBundle\Entity\User

        Tva:
            class: MainBundle\Entity\Tva
            list:
                fields:
                - "valeur"
                - "name"
            form:
                fields:
                    - "name"
                    - "valeur"

        Specialitylist:
            list:
                title: "Liste de spécialités"
                fields:
                    - "title"
                    - "specialitylistName"
            show:
                fields:
                    - "title"
                    - { property: 'specialitylistFile', type: 'vich_image', base_path: %app.path.specialitylist_images% }
            form:
                fields:
                    - "title"
                    - { property: 'specialitylistFile', type: 'vich_image', label: 'Fichier image', base_path: %app.path.specialitylist_images%  }
            class: MainBundle\Entity\Specialitylist

    site_name: "Admin Bambou d'Afrique"
    design:
        brand_color: '#CC4324'
        menu: [{ entity: 'Product', label: 'Plats' }, { entity: 'User', label: 'Utilisateurs' }, 'Commande', 'Tva', { entity: 'Specialitylist', label: 'Spécialités' }]

vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.root_dir%/../web%app.path.product_images%'
            namer: vich_uploader.namer_origname
        specialitylist_images:
            uri_prefix:         '%app.path.specialitylist_images%'
            upload_destination: '%kernel.root_dir%/../web%app.path.specialitylist_images%'
            namer: vich_uploader.namer_origname