
main:
    resource: "@MainBundle/Controller/"
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

bambou_user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /


