# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        main:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern: ^/login$
            anonymous: true

        main_login:
            pattern: ^/admin
            anonymous: false

        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                provider: main
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                default_target_path: index1
                check_path: fos_user_security_check
            anonymous: true
            logout:
                path: fos_user_security_logout
                target: /
            remember_me:
                key: %secret%
            switch_user: { role: ROLE_ADMIN }

    access_control:
        - { path: ^/(_(profiler|wdt)|connexion|inscription|api), role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
