<?php

namespace MainBundle\Repository;

/**
 * AccueilFesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccueilFesRepository extends \Doctrine\ORM\EntityRepository
{
}
