<?php

namespace MainBundle\Repository;

/**
 * AccueilCasaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccueilCasaRepository extends \Doctrine\ORM\EntityRepository
{
}
