<?php

namespace MainBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByBill($user)
    {
        $qb = $this
            ->createQueryBuilder('u')
            ->where('u.user = :user')
            ->andWhere('u.valider = 1')
            ->andWhere('u.reference != 0')
            ->orderBy('u.id')
            ->setParameter('user', $user)
        ;

        return $qb->getQuery()->getResult();

    }
}
