<?php

namespace MainBundle\Repository;

/**
 * ImageMurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageMurRepository extends \Doctrine\ORM\EntityRepository
{
}
