<?php

namespace MainBundle\Repository;

/**
 * SpecialitylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialitylistRepository extends \Doctrine\ORM\EntityRepository
{
}
