main:
    resource: "@MainBundle/Controller/MainController.php"
    prefix:    /
    type:      annotation

test:
    resource: "@MainBundle/Controller/TestController.php"
    prefix:    /
    type:      annotation







