services:
#    main.example:
#        class: MainBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    main.translation_listener:
        class: MainBundle\Translation\TranslationListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    main.doctrine.contact_listener:
        class:     MainBundle\DoctrineListener\ContactListener
        arguments: [@mailer]
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    bambou.mailer:
        class: UserBundle\Services\MailingService
        arguments: [@mailer, @twig, @service_container, @doctrine.orm.entity_manager]

    bambou.calendar:
        class: MainBundle\Services\Calendar

    tva:
        class: MainBundle\Twig\Extension\TvaExtension
        tags:
            - { name: twig.extension}

    montant_tva:
        class: MainBundle\Twig\Extension\MontantTvaExtension
        tags:
            - { name: twig.extension}

    redirection_listener:
        class: MainBundle\Services\RedirectionListener
        arguments: [@service_container, @session]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest}

    set_new_reference:
        class: MainBundle\Services\GetReference
        arguments: [@security.context, @doctrine.orm.entity_manager]